# Generated by Django 4.1.4 on 2022-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_on', models.DateTimeField(auto_created=True)),
                ('cvkey', models.CharField(default='missing', max_length=250)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
