# Generated by Django 4.1.4 on 2022-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvapikey',
            name='used_on',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
