# Generated by Django 4.1.4 on 2023-01-01 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvul', '0002_alter_cvapikey_used_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Valentin Raica', max_length=250)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('age', models.IntegerField(blank=True, default=30, null=True)),
                ('current_position', models.CharField(blank=True, max_length=250, null=True)),
                ('months_on_position', models.IntegerField(blank=True, null=True)),
                ('previous_jobs', models.JSONField(default=[])),
                ('last_studies', models.CharField(blank=True, max_length=250, null=True)),
                ('stack', models.JSONField(default={})),
                ('hobbies', models.JSONField(default=[])),
                ('cv_last_update', models.DateField(default=datetime.datetime(2023, 1, 1, 21, 44, 50, 532595))),
            ],
        ),
    ]
