# Generated by Django 4.1.4 on 2023-01-01 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvul', '0003_cvdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocument',
            name='cv_last_update',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 21, 45, 6, 159517)),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='stack',
            field=models.JSONField(default=dict),
        ),
    ]
